# Generated by Django 3.0.4 on 2020-04-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Coordinador',
            new_name='coordinador',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Creditos',
            new_name='creditos',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Fecha_fin',
            new_name='fecha_fin',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Fecha_inicio',
            new_name='fecha_inicio',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Idioma',
            new_name='idioma',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='coordinador',
            name='username',
        ),
    ]
