# Generated by Django 3.0.5 on 2020-04-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_auth', '0002_auto_20200423_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinador',
            name='codigo_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
