# Generated by Django 3.0.4 on 2020-04-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('countryisocode', models.CharField(max_length=5)),
                ('date', models.CharField(max_length=4)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
